"""
GraphRouter++ Hetero-GNN with query-level listwise ranking loss.

Why this script exists:
    The regression Hetero-GNN can collapse to a fixed prompt-model policy because
    MSE rewards do not directly optimize the query-level argmax decision.
    This version keeps the graph-based/GNN formulation, but trains the router to
    rank the 36 prompt-model actions within each query.

Node types:
    task, query, prompt, model

Scoring:
    s(q,p,m) = MLP([h_q, h_p, h_m, h_q*h_p, h_q*h_m, h_p*h_m])

Default loss:
    listwise KL between softmax(predicted scores) and softmax(true rewards / T)
    within each query.

Run:
    CUDA_VISIBLE_DEVICES=1 python train_router_heterognn_rank_qnorm.py

Requires node description embeddings generated by:
    python scripts/build_node_description_embeddings.py
"""

from __future__ import annotations

import argparse
import json
import random
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

import torch
import torch.nn as nn
import torch.nn.functional as F


DEFAULT_DATA_PATH = Path("data/interaction_logs/grpp_il_v1/router_bipartite_qnorm.jsonl")
DEFAULT_QUERY_EMB_PATH = Path("data/router/query_embeddings.pt")
DEFAULT_TASK_EMB_PATH = Path("data/router/task_embeddings.pt")
DEFAULT_PROMPT_EMB_PATH = Path("data/router/prompt_embeddings.pt")
DEFAULT_MODEL_EMB_PATH = Path("data/router/model_embeddings.pt")
DEFAULT_OUTPUT_DIR = Path("outputs/router_heterognn_rank_qnorm")

LAMBDA_CONFIGS = [
    ("reward_qnorm_lam_01", 0.1),
    ("reward_qnorm_lam_05", 0.5),
    ("reward_qnorm_lam_09", 0.9),
]

TASK_TO_ID = {"gsm8k": 0, "hotpotqa": 1, "squad": 2, "alpaca": 3}
PROMPT_TO_ID = {"direct": 0, "cot": 1, "decompose": 2, "selfcheck": 3}
MODEL_TO_ID = {
    "mistral-7b": 0,
    "qwen2.5-7b": 1,
    "llama3.1-8b": 2,
    "qwen2.5-14b": 3,
    "yi-34b": 4,
    "codellama-34b": 5,
    "mixtral-8x7b": 6,
    "llama3.1-70b": 7,
    "qwen2.5-72b": 8,
}

NODE_TYPES = ("task", "query", "prompt", "model")
RELATIONS = {
    "task_to_query": ("task", "query"),
    "query_to_task": ("query", "task"),
    "prompt_to_query": ("prompt", "query"),
    "query_to_prompt": ("query", "prompt"),
    "model_to_query": ("model", "query"),
    "query_to_model": ("query", "model"),
    "prompt_to_model": ("prompt", "model"),
    "model_to_prompt": ("model", "prompt"),
}


def set_seed(seed: int) -> None:
    random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def load_jsonl(path: Path) -> List[dict]:
    rows = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                rows.append(json.loads(line))
    return rows


def load_tensor(path: Path) -> torch.Tensor:
    obj = torch.load(path, map_location="cpu")
    if isinstance(obj, torch.Tensor):
        return obj.float()
    if isinstance(obj, dict):
        # Accept either a direct tensor under common keys or a dict id -> tensor.
        for key in ("embeddings", "tensor", "x"):
            if key in obj and isinstance(obj[key], torch.Tensor):
                return obj[key].float()
        vals = list(obj.values())
        if vals and all(isinstance(v, torch.Tensor) for v in vals):
            return torch.stack([v.float() for v in vals], dim=0)
    raise TypeError(f"Unsupported tensor file format: {path}")


@dataclass(frozen=True)
class ActionExample:
    qid: str
    task: str
    task_id: int
    prompt: str
    prompt_id: int
    model: str
    model_id: int
    reward: float
    performance: float
    cost: float


def build_examples(rows: List[dict], query_embs: Dict[str, torch.Tensor], reward_key: str) -> List[ActionExample]:
    examples = []
    for row in rows:
        qid = row["qid"]
        task = row["task"]
        if qid not in query_embs or task not in TASK_TO_ID:
            continue
        for edge in row.get("action_edges", []):
            prompt = edge.get("prompt")
            model = edge.get("model")
            if prompt not in PROMPT_TO_ID or model not in MODEL_TO_ID:
                continue
            if reward_key not in edge or edge.get("performance") is None or edge.get("cost_norm_query") is None:
                continue
            examples.append(
                ActionExample(
                    qid=qid,
                    task=task,
                    task_id=TASK_TO_ID[task],
                    prompt=prompt,
                    prompt_id=PROMPT_TO_ID[prompt],
                    model=model,
                    model_id=MODEL_TO_ID[model],
                    reward=float(edge[reward_key]),
                    performance=float(edge["performance"]),
                    cost=float(edge["cost_norm_query"]),
                )
            )
    if not examples:
        raise RuntimeError(f"No examples found for reward key {reward_key}")
    return examples


def split_qids(examples: List[ActionExample], train_ratio: float, val_ratio: float) -> Tuple[set, set, set]:
    qids = sorted({ex.qid for ex in examples})
    random.shuffle(qids)
    n = len(qids)
    n_train = int(n * train_ratio)
    n_val = int(n * val_ratio)
    return set(qids[:n_train]), set(qids[n_train : n_train + n_val]), set(qids[n_train + n_val :])


def filter_examples(examples: List[ActionExample], qids: set) -> List[ActionExample]:
    return [ex for ex in examples if ex.qid in qids]


def edge_index(edges: Iterable[Tuple[int, int]]) -> torch.Tensor:
    edges = list(edges)
    if not edges:
        return torch.empty((2, 0), dtype=torch.long)
    return torch.tensor(edges, dtype=torch.long).t().contiguous()


@dataclass
class HeteroGraph:
    x_dict: Dict[str, torch.Tensor]
    edge_index_dict: Dict[str, torch.Tensor]
    qid_to_local: Dict[str, int]

    def to(self, device: torch.device) -> "HeteroGraph":
        return HeteroGraph(
            x_dict={k: v.to(device) for k, v in self.x_dict.items()},
            edge_index_dict={k: v.to(device) for k, v in self.edge_index_dict.items()},
            qid_to_local=self.qid_to_local,
        )


def build_graph(
    qids: set,
    rows: List[dict],
    query_embs: Dict[str, torch.Tensor],
    task_embs: torch.Tensor,
    prompt_embs: torch.Tensor,
    model_embs: torch.Tensor,
) -> HeteroGraph:
    selected = [r for r in rows if r["qid"] in qids and r["qid"] in query_embs and r["task"] in TASK_TO_ID]
    selected = sorted(selected, key=lambda r: r["qid"])
    if not selected:
        raise RuntimeError("Cannot build graph with zero selected queries.")

    qid_to_local = {row["qid"]: i for i, row in enumerate(selected)}
    query_x = torch.stack([query_embs[row["qid"]].float() for row in selected], dim=0)

    tq, qt, pq, qp, mq, qm = [], [], [], [], [], []
    for row in selected:
        q = qid_to_local[row["qid"]]
        t = TASK_TO_ID[row["task"]]
        tq.append((t, q))
        qt.append((q, t))
        for p in PROMPT_TO_ID.values():
            pq.append((p, q))
            qp.append((q, p))
        for m in MODEL_TO_ID.values():
            mq.append((m, q))
            qm.append((q, m))

    pm = [(p, m) for p in PROMPT_TO_ID.values() for m in MODEL_TO_ID.values()]
    mp = [(m, p) for p in PROMPT_TO_ID.values() for m in MODEL_TO_ID.values()]

    return HeteroGraph(
        x_dict={
            "query": query_x,
            "task": task_embs.float(),
            "prompt": prompt_embs.float(),
            "model": model_embs.float(),
        },
        edge_index_dict={
            "task_to_query": edge_index(tq),
            "query_to_task": edge_index(qt),
            "prompt_to_query": edge_index(pq),
            "query_to_prompt": edge_index(qp),
            "model_to_query": edge_index(mq),
            "query_to_model": edge_index(qm),
            "prompt_to_model": edge_index(pm),
            "model_to_prompt": edge_index(mp),
        },
        qid_to_local=qid_to_local,
    )


class HeteroSageLayer(nn.Module):
    def __init__(self, hidden_dim: int, dropout: float):
        super().__init__()
        self.self_lin = nn.ModuleDict({nt: nn.Linear(hidden_dim, hidden_dim) for nt in NODE_TYPES})
        self.rel_lin = nn.ModuleDict({rel: nn.Linear(hidden_dim, hidden_dim, bias=False) for rel in RELATIONS})
        self.norm = nn.ModuleDict({nt: nn.LayerNorm(hidden_dim) for nt in NODE_TYPES})
        self.dropout = nn.Dropout(dropout)

    def forward(self, h: Dict[str, torch.Tensor], edge_index_dict: Dict[str, torch.Tensor]) -> Dict[str, torch.Tensor]:
        device = next(iter(h.values())).device
        aggs = {nt: torch.zeros_like(h[nt]) for nt in NODE_TYPES}
        for rel, (src_type, dst_type) in RELATIONS.items():
            ei = edge_index_dict[rel]
            if ei.numel() == 0:
                continue
            src, dst = ei[0], ei[1]
            msg = self.rel_lin[rel](h[src_type][src])
            out = torch.zeros_like(h[dst_type])
            out.index_add_(0, dst, msg)
            deg = torch.zeros(h[dst_type].size(0), dtype=h[dst_type].dtype, device=device)
            deg.index_add_(0, dst, torch.ones_like(dst, dtype=h[dst_type].dtype))
            aggs[dst_type] = aggs[dst_type] + out / deg.clamp_min(1.0).unsqueeze(-1)

        new_h = {}
        for nt in NODE_TYPES:
            z = self.self_lin[nt](h[nt]) + aggs[nt]
            z = self.norm[nt](z)
            z = F.relu(z)
            new_h[nt] = self.dropout(z)
        return new_h


class GraphRouterPPRankGNN(nn.Module):
    def __init__(self, query_dim: int, node_desc_dim: int, hidden_dim: int, num_layers: int, dropout: float):
        super().__init__()
        self.query_proj = nn.Linear(query_dim, hidden_dim)
        self.task_proj = nn.Linear(node_desc_dim, hidden_dim)
        self.prompt_proj = nn.Linear(node_desc_dim, hidden_dim)
        self.model_proj = nn.Linear(node_desc_dim, hidden_dim)
        self.layers = nn.ModuleList([HeteroSageLayer(hidden_dim, dropout) for _ in range(num_layers)])
        # Rich query-action interaction scorer. Still GNN-based because inputs are contextualized h_*.
        scorer_in = hidden_dim * 6
        self.scorer = nn.Sequential(
            nn.Linear(scorer_in, hidden_dim),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim, hidden_dim // 2),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim // 2, 1),
        )

    def encode(self, graph: HeteroGraph) -> Dict[str, torch.Tensor]:
        h = {
            "query": self.query_proj(graph.x_dict["query"]),
            "task": self.task_proj(graph.x_dict["task"]),
            "prompt": self.prompt_proj(graph.x_dict["prompt"]),
            "model": self.model_proj(graph.x_dict["model"]),
        }
        for layer in self.layers:
            h = layer(h, graph.edge_index_dict)
        return h

    def score(self, h: Dict[str, torch.Tensor], q_idx: torch.Tensor, p_idx: torch.Tensor, m_idx: torch.Tensor) -> torch.Tensor:
        hq = h["query"][q_idx]
        hp = h["prompt"][p_idx]
        hm = h["model"][m_idx]
        x = torch.cat([hq, hp, hm, hq * hp, hq * hm, hp * hm], dim=-1)
        return self.scorer(x).squeeze(-1)


def tensorize(examples: List[ActionExample], graph: HeteroGraph, device: torch.device) -> Dict[str, torch.Tensor]:
    return {
        "q_idx": torch.tensor([graph.qid_to_local[ex.qid] for ex in examples], dtype=torch.long, device=device),
        "p_idx": torch.tensor([ex.prompt_id for ex in examples], dtype=torch.long, device=device),
        "m_idx": torch.tensor([ex.model_id for ex in examples], dtype=torch.long, device=device),
        "reward": torch.tensor([ex.reward for ex in examples], dtype=torch.float32, device=device),
    }


def group_indices_by_qid(examples: List[ActionExample], device: torch.device) -> List[torch.Tensor]:
    groups = defaultdict(list)
    for i, ex in enumerate(examples):
        groups[ex.qid].append(i)
    return [torch.tensor(idxs, dtype=torch.long, device=device) for _, idxs in sorted(groups.items())]


def listwise_loss(scores: torch.Tensor, rewards: torch.Tensor, groups: List[torch.Tensor], temperature: float, mode: str) -> torch.Tensor:
    losses = []
    for idx in groups:
        s = scores[idx]
        r = rewards[idx]
        if mode == "ce":
            target = torch.argmax(r).view(1)
            losses.append(F.cross_entropy(s.view(1, -1), target))
        elif mode == "soft_kl":
            target = F.softmax(r / temperature, dim=0)
            log_probs = F.log_softmax(s, dim=0)
            losses.append(F.kl_div(log_probs, target, reduction="sum"))
        elif mode == "hybrid":
            target = torch.argmax(r).view(1)
            ce = F.cross_entropy(s.view(1, -1), target)
            soft = F.softmax(r / temperature, dim=0)
            kl = F.kl_div(F.log_softmax(s, dim=0), soft, reduction="sum")
            losses.append(0.5 * ce + 0.5 * kl)
        else:
            raise ValueError(f"Unknown loss mode: {mode}")
    return torch.stack(losses).mean()


@torch.no_grad()
def evaluate(model: GraphRouterPPRankGNN, graph: HeteroGraph, examples: List[ActionExample], device: torch.device) -> dict:
    model.eval()
    h = model.encode(graph)
    data = tensorize(examples, graph, device)
    scores = model.score(h, data["q_idx"], data["p_idx"], data["m_idx"]).detach().cpu().tolist()

    by_qid = defaultdict(list)
    for score, ex in zip(scores, examples):
        by_qid[ex.qid].append({
            "score": float(score),
            "reward": ex.reward,
            "performance": ex.performance,
            "cost": ex.cost,
            "prompt": ex.prompt,
            "model": ex.model,
            "task": ex.task,
        })

    chosen = [max(cands, key=lambda x: x["score"]) for cands in by_qid.values()]
    prompt_counts, model_counts, task_counts = defaultdict(int), defaultdict(int), defaultdict(int)
    for row in chosen:
        prompt_counts[row["prompt"]] += 1
        model_counts[row["model"]] += 1
        task_counts[row["task"]] += 1

    return {
        "queries": len(chosen),
        "avg_reward": sum(x["reward"] for x in chosen) / len(chosen),
        "avg_performance": sum(x["performance"] for x in chosen) / len(chosen),
        "avg_cost": sum(x["cost"] for x in chosen) / len(chosen),
        "prompt_counts": dict(prompt_counts),
        "model_counts": dict(model_counts),
        "task_counts": dict(task_counts),
    }


def train_one_lambda(reward_key: str, lam: float, rows: List[dict], query_embs: Dict[str, torch.Tensor],
                     task_embs: torch.Tensor, prompt_embs: torch.Tensor, model_embs: torch.Tensor,
                     args: argparse.Namespace, device: torch.device) -> dict:
    examples = build_examples(rows, query_embs, reward_key)
    train_qids, val_qids, test_qids = split_qids(examples, args.train_ratio, args.val_ratio)
    train_ex = filter_examples(examples, train_qids)
    val_ex = filter_examples(examples, val_qids)
    test_ex = filter_examples(examples, test_qids)

    train_graph = build_graph(train_qids, rows, query_embs, task_embs, prompt_embs, model_embs).to(device)
    val_graph = build_graph(train_qids | val_qids, rows, query_embs, task_embs, prompt_embs, model_embs).to(device)
    test_graph = build_graph(train_qids | val_qids | test_qids, rows, query_embs, task_embs, prompt_embs, model_embs).to(device)

    train_data = tensorize(train_ex, train_graph, device)
    train_groups = group_indices_by_qid(train_ex, device)
    query_dim = next(iter(query_embs.values())).shape[0]
    node_desc_dim = task_embs.shape[1]

    model = GraphRouterPPRankGNN(
        query_dim=query_dim,
        node_desc_dim=node_desc_dim,
        hidden_dim=args.hidden_dim,
        num_layers=args.num_layers,
        dropout=args.dropout,
    ).to(device)
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)

    best_val, best_state, stale = -1e9, None, 0
    print(f"\n==== TRAINING RANK-GNN {reward_key} / lambda={lam} ====")
    print(f"Actions: total={len(examples)} train={len(train_ex)} val={len(val_ex)} test={len(test_ex)}")
    print(f"Queries: train={len(train_qids)} val={len(val_qids)} test={len(test_qids)}")
    print(f"Loss: {args.loss} | temperature={args.temperature}")

    for epoch in range(1, args.epochs + 1):
        model.train()
        h = model.encode(train_graph)
        scores = model.score(h, train_data["q_idx"], train_data["p_idx"], train_data["m_idx"])
        loss = listwise_loss(scores, train_data["reward"], train_groups, args.temperature, args.loss)
        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), args.grad_clip)
        optimizer.step()

        val_metrics = evaluate(model, val_graph, val_ex, device)
        print(
            f"Epoch {epoch:03d} | train_loss={loss.item():.6f} | "
            f"val_R={val_metrics['avg_reward']:.6f} | "
            f"val_P={val_metrics['avg_performance']:.6f} | val_C={val_metrics['avg_cost']:.6f}"
        )

        if val_metrics["avg_reward"] > best_val:
            best_val = val_metrics["avg_reward"]
            best_state = {k: v.detach().cpu() for k, v in model.state_dict().items()}
            stale = 0
        else:
            stale += 1
            if args.patience > 0 and stale >= args.patience:
                print(f"Early stopping at epoch {epoch}.")
                break

    if best_state is None:
        raise RuntimeError("No checkpoint selected.")
    model.load_state_dict(best_state)
    test_metrics = evaluate(model, test_graph, test_ex, device)

    args.output_dir.mkdir(parents=True, exist_ok=True)
    model_path = args.output_dir / f"router_rankgnn_{reward_key}_seed{args.seed}.pt"
    torch.save({
        "state_dict": best_state,
        "lambda_key": reward_key,
        "lambda": lam,
        "config": vars(args),
        "task_to_id": TASK_TO_ID,
        "prompt_to_id": PROMPT_TO_ID,
        "model_to_id": MODEL_TO_ID,
    }, model_path)

    result = {
        "lambda_key": reward_key,
        "lambda": lam,
        "queries": test_metrics["queries"],
        "P": test_metrics["avg_performance"],
        "C": test_metrics["avg_cost"],
        "R": test_metrics["avg_reward"],
        "prompt_counts": test_metrics["prompt_counts"],
        "model_counts": test_metrics["model_counts"],
        "task_counts": test_metrics["task_counts"],
        "model_path": str(model_path),
    }
    print("\n==== TEST RESULTS ====")
    print(f"queries={result['queries']}")
    print(f"P={result['P']:.6f} C={result['C']:.6f} R={result['R']:.6f}")
    print(f"prompt_counts={result['prompt_counts']}")
    print(f"model_counts={result['model_counts']}")
    print(f"saved_model={model_path}")
    return result


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Train GraphRouter++ Rank-GNN with qnorm rewards.")
    p.add_argument("--data-path", type=Path, default=DEFAULT_DATA_PATH)
    p.add_argument("--query-emb-path", type=Path, default=DEFAULT_QUERY_EMB_PATH)
    p.add_argument("--task-emb-path", type=Path, default=DEFAULT_TASK_EMB_PATH)
    p.add_argument("--prompt-emb-path", type=Path, default=DEFAULT_PROMPT_EMB_PATH)
    p.add_argument("--model-emb-path", type=Path, default=DEFAULT_MODEL_EMB_PATH)
    p.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    p.add_argument("--device", default="cuda:0" if torch.cuda.is_available() else "cpu")
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--epochs", type=int, default=80)
    p.add_argument("--patience", type=int, default=20)
    p.add_argument("--lr", type=float, default=5e-4)
    p.add_argument("--weight-decay", type=float, default=1e-4)
    p.add_argument("--hidden-dim", type=int, default=256)
    p.add_argument("--num-layers", type=int, default=2)
    p.add_argument("--dropout", type=float, default=0.15)
    p.add_argument("--grad-clip", type=float, default=1.0)
    p.add_argument("--loss", choices=["soft_kl", "ce", "hybrid"], default="hybrid")
    p.add_argument("--temperature", type=float, default=0.05)
    p.add_argument("--train-ratio", type=float, default=0.70)
    p.add_argument("--val-ratio", type=float, default=0.15)
    return p.parse_args()


def main() -> None:
    args = parse_args()
    set_seed(args.seed)
    device = torch.device(args.device)

    print("==== TRAIN GRAPHROUTER++ RANK-GNN QNORM ====")
    print("Device:", device)
    print("Data:", args.data_path)
    print("Query embeddings:", args.query_emb_path)
    print("Task embeddings:", args.task_emb_path)
    print("Prompt embeddings:", args.prompt_emb_path)
    print("Model embeddings:", args.model_emb_path)

    rows = load_jsonl(args.data_path)
    query_embs = torch.load(args.query_emb_path, map_location="cpu")
    task_embs = load_tensor(args.task_emb_path)
    prompt_embs = load_tensor(args.prompt_emb_path)
    model_embs = load_tensor(args.model_emb_path)

    assert task_embs.shape[0] == len(TASK_TO_ID), f"Expected {len(TASK_TO_ID)} task embeddings, got {task_embs.shape}"
    assert prompt_embs.shape[0] == len(PROMPT_TO_ID), f"Expected {len(PROMPT_TO_ID)} prompt embeddings, got {prompt_embs.shape}"
    assert model_embs.shape[0] == len(MODEL_TO_ID), f"Expected {len(MODEL_TO_ID)} model embeddings, got {model_embs.shape}"

    all_results = []
    for reward_key, lam in LAMBDA_CONFIGS:
        set_seed(args.seed)
        all_results.append(train_one_lambda(reward_key, lam, rows, query_embs, task_embs, prompt_embs, model_embs, args, device))

    args.output_dir.mkdir(parents=True, exist_ok=True)
    result_path = args.output_dir / f"router_heterognn_rank_qnorm_results_seed{args.seed}.json"
    with result_path.open("w", encoding="utf-8") as f:
        json.dump(all_results, f, indent=2)

    print("\n==== OVERLEAF ROW ====")
    vals = []
    for r in all_results:
        vals.extend([f"{r['P']:.3f}", f"{r['C']:.3f}", f"{r['R']:.3f}"])
    print("GraphRouter++ Rank-GNN (qnorm) & " + " & ".join(vals) + r" \\")
    print(f"\nSaved results: {result_path}")


if __name__ == "__main__":
    main()
